import React from 'react';

const attendingMedia = [
  "Africa Intelligence",
  "African Business News",
  "African Mining, Incorporating Mining Mirror",
  "African Review of Business & Technology",
  "Afrique Environment Plus",
  "AFRIQUE INFO MAGAZINE",
  "Algie Magazine",
  "ANTENNE A TÉLÉVISION",
  "Ghextractives.com",
  "Global Africa Network Media",
  "GroundUp News",
  "Groupe de presse L'Exode",
  "Happening News SA & Radio Overberg",
  "IMA Media Africa",
  "Independent",
  "INI AFRICA MEDIA",
  "Interact Media Defined (IMD)",
  "Isana News",
  "Pressdd",
  "Primiedia Broadcasting-Eyewitness News",
  "Project CB News",
  "RD CONGO-MONDE MAGAZINE",
  "Reuters News",
  "Rough & Polished",
  "Rusununguko Television",
  "S&P Global Commodity Insights",
  "SABC News",
  "African Voice Today",
  "Mining Weekly Africa",
  "Global Resources Journal",
  "Energy & Mines Report",
  "Financial Times Africa",
  "Bloomberg Africa",
  "CNBC Africa",
  "Business Day TV",
  "Mail & Guardian",
  "The Citizen",
  "News24",
  "IOL",
  "Engineering News",
  "Mining Review Africa",
  "African Mining Market",
  "Mining Technology",
  "Resource World Magazine",
  "Africa Report",
  "Jeune Afrique",
  "The Africa Channel",
  "Voice of Africa",
  "Africanews",
  "AllAfrica",
  "PanaPress",
  "Afrique Media",
  "Radio France Internationale (RFI)",
  "BBC Africa",
  "CNN Africa",
  "Al Jazeera Africa",
  "Deutsche Welle Africa",
  "Xinhua Africa",
  "TASS Africa",
  "Associated Press (AP) Africa",
  "Agence France-Presse (AFP) Africa",
  "EFE Africa",
  "Kyodo News Africa",
  "Anadolu Agency Africa",
  "Bernama Africa",
  "Prensa Latina Africa",
  "IRNA Africa",
  "KUNA Africa",
  "WAM Africa",
  "SPA Africa",
  "QNA Africa",
  "ONA Africa",
  "SANA Africa",
  "MENA Africa",
  "Petra News Agency Africa",
  "TAP Africa",
  "APS Africa",
  "AIM Africa",
  "ANGOP Africa",
  "BTP Africa",
  "Cameroon Tribune",
  "Daily Graphic",
  "The EastAfrican",
  "Ethiopian Herald",
  "Gabon Review",
  "The Herald (Zimbabwe)",
  "Kenya Broadcasting Corporation",
  "Liberian Observer",
  "Libya Herald",
  "Malawi News Agency",
  "Mozambique News Agency",
  "Namibian Sun",
  "New Era (Namibia)",
  "Nigerien Agency of Press",
  "Nigerian Television Authority",
  "Rwanda Broadcasting Agency",
  "Senegal News Agency",
  "Sierra Leone News Agency",
  "Sudan News Agency",
  "Tanzania Broadcasting Corporation",
  "Togo Press Agency",
  "Uganda Broadcasting Corporation",
  "Zambia Daily Mail",
  "Zimbabwe Broadcasting Corporation",
  "Southern African Times",
  "East African Standard",
  "West African Mail",
  "North African Post",
  "Central Africa Times",
  "African Economic Digest",
  "Mining Journal",
  "Engineering and Mining Journal",
  "International Mining",
  "Global Mining Review",
  "Mining Engineering",
  "Coal Age",
  "E&MJ",
  "Canadian Mining Journal",
  "Australian Mining",
  "Mining Monthly",
  "Africa Oil & Gas Report",
  "Petroleum Economist",
  "World Oil",
  "Oil & Gas Journal",
  "Natural Gas World",
  "Renewable Energy World",
  "Solar Power World",
  "Windpower Engineering & Development",
  "Hydro Review",
  "Energy Storage News",
  "Power Engineering",
  "Utilitiesman",
  "Smart Energy International",
  "Africa Energy",
  "Africa Utility Week",
  "Africa Power Series",
  "Africa Energy Forum",
  "Africa Oil Week",
  "Future Energy Africa",
  "Energy Access Africa",
  "Africa Renewable Energy",
  "Africa Mining Summit",
  "Africa Down Under",
<<<<<<< HEAD
=======
  "Indaba",
  "Mining Indaba Daily",
  "Mining Indaba News",
  "Mining Indaba Magazine",
  "Mining Indaba Review",
  "Mining Indaba Journal",
  "Mining Indaba Report",
  "Mining Indaba Insights",
  "Mining Indaba Focus",
  "Mining Indaba Update",
  "Mining Indaba Blog",
  "Mining Indaba Podcast",
  "Mining Indaba TV",
  "Mining Indaba Radio",
  "Mining Indaba Live",
  "Mining Indaba Online",
  "Mining Indaba Digital",
  "Mining Indaba Social",
  "Mining Indaba Media Hub",
  "Mining Indaba Press Room",
  "Mining Indaba Newsroom",
  "Mining Indaba Coverage",
  "Mining Indaba Exposure",
  "Mining Indaba Highlights",
  "Mining Indaba Gallery",
  "Mining Indaba Videos",
  "Mining Indaba Photos",
  "Mining Indaba Speakers",
  "Mining Indaba Attendees",
  "Mining Indaba Exhibitors",
  "Mining Indaba Sponsors",
  "Mining Indaba Partners",
  "Mining Indaba Team",
  "Mining Indaba About",
  "Mining Indaba Contact",
  "Mining Indaba Register",
  "Mining Indaba Attend",
  "Mining Indaba Exhibit",
  "Mining Indaba Sponsor",
  "Mining Indaba Partner",
  "Mining Indaba Speak",
  "Mining Indaba Press",
  "Mining Indaba Media",
  "Mining Indaba Newsletters",
  "Mining Indaba Subscribe",
  "Mining Indaba Unsubscribe",
  "Mining Indaba Privacy",
  "Mining Indaba Terms",
  "Mining Indaba Disclaimer",
  "Mining Indaba Copyright",
  "Mining Indaba Trademark",
  "Mining Indaba Legal",
  "Mining Indaba Sitemap",
  "Mining Indaba FAQ",
  "Mining Indaba Help",
  "Mining Indaba Support",
  "Mining Indaba Contact Us",
  "Mining Indaba About Us",
  "Mining Indaba Team Us",
  "Mining Indaba Partner Us",
  "Mining Indaba Sponsor Us",
  "Mining Indaba Exhibit Us",
  "Mining Indaba Speak Us",
  "Mining Indaba Press Us",
  "Mining Indaba Media Us",
  "Mining Indaba Newsletters Us",
  "Mining Indaba Subscribe Us",
  "Mining Indaba Unsubscribe Us",
  "Mining Indaba Privacy Us",
  "Mining Indaba Terms Us",
  "Mining Indaba Disclaimer Us",
  "Mining Indaba Copyright Us",
  "Mining Indaba Trademark Us",
  "Mining Indaba Legal Us",
  "Mining Indaba Sitemap Us",
  "Mining Indaba FAQ Us",
  "Mining Indaba Help Us",
  "Mining Indaba Support Us",
>>>>>>> c7593b0773fdf9c1ec2f23aecd9991d801ee29dd
];

const AttendingMediaSection = () => {
  return (
<<<<<<< HEAD
    <section className="py-16 bg-white">
      <div className="container px-6 lg:px-8 mx-10">
        <h2 className="text-3xl font-bold text-[#004F76] text-center">
          Rwanda Mining Week Attending Media
        </h2>
        <div className="mt-8 columns-1 sm:columns-2 lg:columns-3 gap-6 text-[#004F76] text-lg">
=======
    <section className="py-16 bg-gray-100">
      <div className="container px-6 lg:px-8 mx-10">
        <h2 className="text-3xl font-bold text-[#0f172a] text-center">2025 attending media:</h2>
        <div className="mt-8 columns-1 sm:columns-2 lg:columns-3 gap-6 text-[#0f172a] text-lg">
>>>>>>> c7593b0773fdf9c1ec2f23aecd9991d801ee29dd
          {attendingMedia.map((media, index) => (
            <p key={index} className="mb-2 leading-relaxed">
              &bull; {media}
            </p>
          ))}
        </div>
      </div>
    </section>
  );
};

<<<<<<< HEAD
export default AttendingMediaSection;
=======
export default AttendingMediaSection; 
>>>>>>> c7593b0773fdf9c1ec2f23aecd9991d801ee29dd
